### PR TITLE
#167147965 built sign-in page

### PR DESCRIPTION
**Pull request by placideirandora**
#### What does this PR do?
It creates a sign-in page.

#### Description of Task to be completed?
1. It creates and adds a sign-in page to the sign-in button on the homepage.
2. It adjusts some HTML and CSS of the homepage to maintain consistency.

#### How should this be manually tested?
Navigate to the homepage page and click on the **Sign In** button and check if you get the to the login form. 

#### Secreenshots

**Desktop Version**

sign-in html

**Mobile Version**

sign-in html-mobile

### CODE REVIEW

**Comment by harerakalex** [comment]
Nice job bro, for me you can merge it.

**Comment by Jkadhuwa** [comment]
Nice work man, a quick suggestion for the mobile version I think it will be better if you would remove the border around the image.

**Comment by raymond42** [comment]
Looks nice, as suggested by @Jkadhuwa you can remove that border around the image or put it on the whole image and the form as it is for the big version to make it consistent

**Comment by placideirandora** [comment]
I will create a Bug or Chore story to work on that because I have already merged the Sign Up page and they have the same mobile versions!

**Pull request merged**
