### PR TITLE
User should be able to view the landing page UI #167148087

### PR DESCRIPTION
**Pull request by malaba6**
**What does this PR do?**
- It creates the landing page for E-Rental website
- Changes the page's background color to darker
- Changes The description's font weight to be more visible

**Description of the task to be completed**
- On the page, create a navigation bar to help the user navigate through the website
- Add a description about the purpose of the site.
- Add a search bar to search for a specific place
- Add a footer
- Change home page's color to white and increase font-weight to be visible

**Relevant PT Stories:**
- [User can view the landing page](https://www.pivotaltracker.com/story/show/167148087)
-  [User can search house in a specific location](https://www.pivotaltracker.com/story/show/167154960)

**Screenshots:**
mob-fix-home
fix-home

@Jkadhuwa , @placideirandora , @raymond42 , @harerakalex

### CODE REVIEW

**Comment by placideirandora** [comment]
I think you should use a light background such as **#f2f2f2;** or any other light one.

**Comment by placideirandora** [comment]
You can merge it!

**Comment by Malaba6** [comment]
@placideirandora last time we agreed on having black as background for the navigation bar

**Comment by harerakalex** [comment]
Well, it's good for me, you should go ahead and merge it.

**Comment by raymond42** [comment]
This is so nice, but could you try to change the font color of the description and try o make it bigger to be more visual and also if you reduce exposure of the background and use the white color for the color of description, I think It would be much better

**Comment by Jkadhuwa** [comment]
I think its cool, but you can add some changes which we have discussed with @raymond42 about the background image saturation and change text color to white. Please would you view the mockup sent to you for insight.

**Comment by malaba6** [comment]
Ok! Cool! on it... thanx

**Comment by raymond42** [comment]
LG

**Comment by bdushimi** [comment]
Please change the labels on a PR once its status changes. The labels on this PR mean that it needs review and it is not yet completed yet it has been merged!

**Pull request merged**
