### PR TITLE
Landlord can post a house for rent #167161225

### PR DESCRIPTION
**Pull request by Jkadhuwa**
**What does this PR do?**
- It creates the landlords' page to post their house

**Description of the task to be completed**
- Created a postHouse.html page which contains a form to enable the landlord to post a house with all 
  relevant information like pictures, location, and prices.

**Relevant PT Stories:**
- [Landlord can post a house](https://www.pivotaltracker.com/story/show/167161225)

**How this can be tested**
 [click here](https://malaba6.github.io/E-Rental/UI/html/postHouse.html)

**Screenshots:**
Screen Shot 2019-07-17 at 16 37 53

 for mobile
Screen Shot 2019-07-17 at 16 39 46

### CODE REVIEW

**Comment by placideirandora** [comment]
You can merge it!

**Comment by malaba6** [comment]
Good job @Jkadhuwa. But I feel like the input borders could be thiner

**Comment by harerakalex** [comment]
Tested and works. So can be merged.

**Comment by placideirandora** [comment]
You can merge!

**Pull request merged**
