### PR TITLE
Landlord should be able to update a house for rent  #167149245

### PR DESCRIPTION
**Pull request by Jkadhuwa**
**What does this PR do?**
- It creates the landlords' page to update their house

**Description of the task to be completed**
- Created a updateHouse.html page which contains a form to enable the landlord to update house information like pictures, and prices.

**Relevant PT Stories:**
- [Landlord can update a house](https://www.pivotaltracker.com/story/show/167149245)

**How this can be tested**
 [click here](https://malaba6.github.io/E-Rental/UI/html/updateHouse.html)

**Screenshots:**
Screen Shot 2019-07-17 at 22 56 40

 for mobile
Screen Shot 2019-07-17 at 22 57 39

### CODE REVIEW

**Comment by malaba6** [comment]
Looks good to me

**Comment by raymond42** [comment]
LG Good job

**Comment by harerakalex** [comment]
Nice job, but remember to add `link` for viewing all house.

**Comment by malaba6** [comment]
I noticed that the nav bar is being overlapped by the picture on the update branch...can you fix that plz?

**Comment by malaba6** [comment]
The signup and login links in the nav bar not working.... If you could fix that as well

**Pull request merged**
