### PR TITLE
User can view all available houses #167154609

### PR DESCRIPTION
**Pull request by raymond42**
**What does this PR do?**
- It creates the user page for viewing all houses

**Description of the task to be completed**
- On the page, shows all the houses that are available for rent

**Relevant PT Stories:**
- [User can view all available houses](https://www.pivotaltracker.com/story/show/167154609)

**How this can be tested**
 [click here](https://malaba6.github.io/E-Rental/UI/html/view_all_available_houses.html)

**Screenshots:**
image

 for mobile
image

### CODE REVIEW

**Comment by malaba6** [comment]
The PR title doesn't look right to me...
Otherwise, We can go with that

**Comment by Jkadhuwa** [comment]
Looks good bro.

**Comment by raymond42** [comment]
> The PR title doesn't look right to me...
> Otherwise, We can go with that

Done

**Comment by harerakalex** [comment]
Wow, I tested this feature, it is working
You can merge it.

**Pull request merged**
