### PR TITLE
User should be able to view a specific house and flag a house #167155025

### PR DESCRIPTION
**Pull request by harerakalex**
### What does this PR do?
- It allows user to view a specific house.
- It allows user to flag a house as fraudulent.
### Description of the task to be completed
- UI that allow user to view a specific house.
- Modal to flag a house as fraudelent
### Relevant PT Stories
- [#167155025 View a specific house](https://www.pivotaltracker.com/story/show/167155025)
- [#167161675 Flag a house](https://www.pivotaltracker.com/story/show/167161675)
### Screenshots
Screen Shot 2019-07-16 at 10 55 47

Screen Shot 2019-07-16 at 10 57 54

Screen Shot 2019-07-16 at 10 57 25

@Jkadhuwa , @placideirandora , @raymond42 ,

### CODE REVIEW

**Comment by malaba6** [comment]
Good job @Carlos...it looks really cool! However, I think that if you changed the font-family of the `main` tag to `font-family: Arial, Helvetica, sans-serif;`,  It would look better and consistent with the rest of the pages. Like this 
Screen Shot 2019-07-16 at 11 55 03

**Comment by raymond42** [comment]
Looks Good. only implement Eric's feedback about the font

**Comment by Jkadhuwa** [comment]
Looks awesome bro.

**Comment by malaba6** [comment]
Looks good!

**Pull request merged**
