### PR TITLE
#167398979 built user sign in endpoint

### PR DESCRIPTION
**Pull request by placideirandora**
#### What does this PR do?
It creates a user sign-in endpoint.

#### Description of Task to be done?
1. It adds a user sign-in controller in the auth controller file.
2. It validates the information submitted during sign-in such as email and password.
3. It adds a route for user sign-in.

#### How should this be manually tested?
1. Start the **Server** and **POSTMAN**.
2. **Browse** the following endpoint route: **localhost:3000/api/auth/signin**.
3. Make sure that you have an account or create one in advance.
4. Submit the required information - **email** and **password** - with **POST** method. 
5. Check if the validations work once you don't submit any of the required information.
6. After passing the validations, you should receive a **200 HTTP Status Code** along with the information related to your account such as firstname, lastname, and email.

### CODE REVIEW

**Comment by harerakalex** [comment]
Looks good, and after testing this endpoint, It is working well.

**Comment by malaba6** [comment]
- @Placide, when the user ties to create an already existing user, the status code is 409 for conflict, not 400, that's a bad request. 
- The password validation is not strong enough. I think that forcing the user to use is strong password is better by including upper and lower cases and symbols in the password.
- When the user uses invalid credentials, the status code is 401, not 400.

**Comment by malaba6** [comment]
- @Placide, when the user ties to create an already existing user, the status code is 409 for conflict, not 400, that's a bad request. 
- The password validation is not strong enough. I think that forcing the user to use is strong password is better by including upper and lower cases and symbols in the password.
- When the user uses invalid credentials, the status code is 401, not 400.

**Comment by malaba6** [comment]
- @Placide, when the user ties to create an already existing user, the status code is 409 for conflict, not 400, that's a bad request. 
- The password validation is not strong enough. I think that forcing the user to use is strong password is better by including upper and lower cases and symbols in the password.
- When the user uses invalid credentials, the status code is 401, not 400.

**Comment by placideirandora** [comment]
Thanks! I'm gonna implement that.

**Comment by raymond42** [comment]
Everything works fine, you can only implement Eric's feedback

**Comment by placideirandora** [comment]
I have implemented all of the feedback!

**Pull request merged**
